### ISSUE TITLE
Variants to current system

### ISSUE THREAD

**Issue by djetelina** [iScrE4m/XLeague#11]
Kyle and I talked for a bit. In order to simplify user experience and still have our account system, it would be great to have chat app/protocol, that had OAuth. We could link chat auth with our database and build gamification etc. on top of that. 

Here's few things we discussed and their advantage/disadvantages
- Slack

https://slack.com/ - They have OAuth, they support bots, but I couldn't figure out a way to embed their client to our frontend
- Twitch.tv IRC server

OAuth present, IRC network, so no need to rewrite our bot logic in something else. Embeding could work either through iframe of their popout chat, or inject OAuth into irc command to connect

I haven't really explored the options indepth too much, as this requries a lot of thinking I cannot afford during exam period. So while I'm busy studying, you can talk here about different variants, solutions, or just say that current system is good enough (GameSurge auth through IRC, separate accounts in our database).

This post might be a bit chaotic, if you need any clarifications, lemme know

**Comment by menocar** [comment]
If I understand correctly the redesign is trying to achieve the following goals:
1. Use an existing chat service for an easier access than IRC.
2. Make use of the OAuth API of the chat service so that you can manipulate it from the XLeague frontend and/or run your bot.
3. Implement SSO using OpenID.

It sounds 1 and 2 are possible with both of those services. I'm not sure about 3, for this the chat service needs to be a OpenID provider, which you should check. Otherwise you need to chose another OpenID provider and let everyone use it to log-in to both XLeague and the chat service.

I'm personally in favor of this idea, even just for 1, as it was unfortunate for me to lose the ability to go back and read the history after my IRCCloud free period is finished. Using OpenID as your authentication method would reduce some work too, for example you no longer need to manage passwords yourself.

One high level comment though is that I think it's overall less work than building a match history recording/processing system on top of XMage to directly changing XMage server code to make information available externally. For example we can change the server to record past match histories, and make them accessible from some URL under xmage.de, then you can just write the part that computes ratings and publish the result. The upside is you don't need to think about your DB scheme in advance, you can update your code anytime and re-process the entire history. Then XLeague can concentrate on the Player DB and building the community of good users, which I think makes sense to exist outside the XMage application.

**Comment by djetelina** [comment]
Yes, you understand it correctly. In ideal scenario, user uses SSO, is redirected to frontend with chat embedded and connected with his account. There can push buttons instead of dealing with chat commands. The chat would still be there to keep everything social and for bot to send replies to actions.

 OpenID is something I really want to do if we were to create account system, because of security. I don't want to store passwords, I don't want to take care of them. I don't want people trying to hack me to check if they are hashed properly. 

To the high level stuff - the problem is, we sometimes user woogerworks server if .de is down, that complicates things a lot. Also I'd love for this system to be built independent where possible, so it can be fit on other games/services too. Custom match history doesn't provide us with as much information (unless we want reporting results to be superpainful), but a simple one of who played who, when and what was the final result sounds like something we should have internally.

**Comment by menocar** [comment]
We can build-in the logs download API to XMage so that we can collect data from woogerworks server too. Regarding the goal to grow XLeague as a generic rating service: I see, I get that you don't feel like investing too much on the MTG specific things, let alone XMage specific things. I guess then it's necessary to build your own system.

**Comment by djetelina** [comment]
Yeah that, but I also like building tools that could potentionally have use elsewhere too.

**Comment by djetelina** [comment]
closed because the project is inactive
